[project]
name = "ai-engineering-sketchpad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.7",
    "openai>=2.16.0",
    "polars>=1.37.1",
]
